{{- if or .Values.portalBff.existingSecret .Values.secretManagement.kubernetesMount.enabled .Values.secretManagement.egress.privateEndpointAllowlist }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edk-enterprise.fullname" . }}-secret-management-manifests
  labels:
    {{- include "edk-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: platform
data:
  {{- if .Values.portalBff.existingSecret }}
  environment.manifest: |
    sec_admin_console_portal_bff_01=ADMIN_CONSOLE_WORKLOAD_CLIENT_SECRET
    sec_0_25_0_rc2_to_0_25_0_rc3_software_kms_password_01=EDK_KEYSTORE_PASSWORD
  {{- end }}
  {{- if .Values.secretManagement.kubernetesMount.enabled }}
  kubernetes-mount.manifest: |
    {{- range $secretId := keys .Values.secretManagement.kubernetesMount.manifest | sortAlpha }}
    {{ $secretId }}={{ index $.Values.secretManagement.kubernetesMount.manifest $secretId }}
    {{- end }}
  {{- end }}
  {{- if .Values.secretManagement.egress.privateEndpointAllowlist }}
  private-endpoints.manifest: |
    {{- range $host := keys .Values.secretManagement.egress.privateEndpointAllowlist | sortAlpha }}
    {{ $host }}={{ join "," (index $.Values.secretManagement.egress.privateEndpointAllowlist $host) }}
    {{- end }}
  {{- end }}
{{- end }}
