{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edk-enterprise.serviceAccountName" . }}
  labels:
    {{- include "edk-enterprise.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and (eq (include "edk-enterprise.topologyMode" .) "distributed") (index .Values.services "platform").enabled .Values.serviceAccount.platform.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edk-enterprise.platformServiceAccountName" . }}
  labels:
    {{- include "edk-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: platform
  {{- with .Values.serviceAccount.platform.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
