apiVersion: v2
name: edk-enterprise
description: EDK enterprise container deployment for KMS, DID, AS, Issuer, Verifier, Wallet Unit, and Wallet Interaction
type: application
version: 0.2.1
appVersion: "0.25.0-SNAPSHOT"
