global:
  imageTag: 0.25.0-SNAPSHOT
  imagePullSecrets:
    - sphereon-nexus
  platformBaseDomain: example.com

database:
  enabled: true
  dialect: postgresql
  platform:
    host: edk-platform.postgres.database.example.net
    port: 5432
    name: platform
    existingSecret: edk-managed-platform-postgres
    usernameKey: username
    passwordKey: password
    networkPolicy:
      ipBlock:
        cidr: 10.42.16.20/32
  tenant:
    host: edk-tenant.postgres.database.example.net
    port: 5432
    name: tenant
    existingSecret: edk-managed-tenant-postgres
    usernameKey: username
    passwordKey: password
    isolation: schema
    schemaPattern: "tenant_{id}"
    networkPolicy:
      ipBlock:
        cidr: 10.42.16.21/32

networkPolicy:
  enabled: true
  allowDnsEgress: true
