global:
  imageTag: 0.25.0-SNAPSHOT
  imagePullSecrets:
    - sphereon-nexus
  platformBaseDomain: example.com

database:
  enabled: true
  dialect: postgresql
  host: edk-prod.postgres.database.example.net
  port: 5432
  name: edk
  existingSecret: edk-managed-postgres
  usernameKey: username
  passwordKey: password
  networkPolicy:
    ipBlock:
      cidr: 10.42.16.20/32

networkPolicy:
  enabled: true
  allowDnsEgress: true
