auth:
  enabled: true
  jwt:
    enabled: true
    issuer: https://as.example.com
    jwksUri: https://as.example.com/.well-known/jwks.json
    audience: edk-enterprise

grpc:
  enabled: false
  authMode: mesh-mtls

podAnnotations:
  sidecar.istio.io/inject: "true"

ingress:
  internal:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
