database:
  existingSecret: edk-postgres
  usernameKey: username
  passwordKey: password

services:
  tenant-as:
    env:
      - name: OAUTH2_SERVER_SIGNING_KEY_REF
        valueFrom:
          secretKeyRef:
            name: edk-as-signing
            key: key-ref
  issuer:
    env:
      - name: OID4VCI_ISSUER_SIGNING_KEY_REF
        valueFrom:
          secretKeyRef:
            name: edk-issuer-signing
            key: key-ref
  tenant-kms:
    env:
      - name: KMS_PROVIDER_CREDENTIALS_REF
        valueFrom:
          secretKeyRef:
            name: edk-kms-provider
            key: credentials-ref
